#!/usr/bin/expect

set host [ lindex $argv 0 ]
set username [ lindex $argv 1 ]
set passwd [ lindex $argv 2 ]
set file [ lindex $argv 3 ]
set path [ lindex $argv 4 ]

puts "push $file to $host $path"
spawn scp $file $username@$host:$path
expect {
    "(yes/no)?" {
        send "yes\n"
        exp_continue
    }

    "(y/n)?" {
        send "y\n"
        exp_continue
    }
    
    "password:" {
        send "$passwd\n"
    }
}

expect eof

